### ISSUE TITLE
rake sample_data fail on new likes

### ISSUE THREAD

**Issue by rsfarzo** [appdev-lessons/photogram-industrial-part-2#1]
The following `app/models/like.rb` constraint in the notes fails during `rake sample_data`:
```
validates :user_id, uniqueness: { scope: :photo_id, message: "has already liked this photo" }
```
Perhaps add an existence check to:
```
        if rand < 0.5
          photo.fans << follower
        end
```

**Comment by bpurinton** [comment]
I may be missing the point, could you provide a bit more detail? Are you referring to an existence check on the validation? Or, do you mean adding something like:

```ruby
if rand < 0.5 && !photo.fans.include?(follower)
  photo.fans << follower
end
```

to the sample data in code block in the lesson?

**Comment by bpurinton** [comment]
I'm re-opening this, since I haven't actually made the lesson change yet.

**Comment by bpurinton** [comment]
Fixed here: https://github.com/appdev-lessons/photogram-industrial-part-2/commit/b9372588165d10252ce898b2ad8b6a81ec068fe2
